### ISSUE TITLE
button to get links to sections 

### ISSUE THREAD

**Issue by ix0rai** [QuiltMC/developer-wiki#100]
![image](https://github.com/QuiltMC/developer-wiki/assets/66223394/18de732e-44c2-4002-845f-a4c8f4fa9b7a)
like the ones on quiltmc.org!
@simpledemonn I hear you like making these

**Comment by simpledemonn** [comment]
It looks like the FontAwesome kit is never loaded but some icons are baked in at compile time, but not link
