### ISSUE TITLE
Lines don't wrap.

### ISSUE THREAD

**Issue by Gingeh** [QuiltMC/developer-wiki#26]
### Issue description

Lines of text continue off-screen instead of wrapping.

![image](https://user-images.githubusercontent.com/39150378/177021918-a034d30b-cf2b-4382-bcd1-871ac2408c85.png)

I am using:

- Firefox 102.0
- Linux Mint 20.2 Uma

**Comment by PinkGoosik** [comment]
same 
![image](https://user-images.githubusercontent.com/56874042/177051541-9ae7774e-b34f-4b7b-a0a3-a5b5fc6370a1.png)

other pages are fine
![image](https://user-images.githubusercontent.com/56874042/177051568-204bbc6e-4e77-4fb7-96e7-5cf78a0e19cf.png)

**Comment by gdude2002** [comment]
This seems to be an issue on the site itself as well - I'll look into it

**Comment by gdude2002** [comment]
This appears to be quite a complex problem, and so far I haven't managed to figure out a way to deal with it. It seems to be an interaction between Bulma's columns and its code blocks - placing code blocks within columns, or columns within columns, causes the content of the right column to become wider than the column itself and everything overflows to the right.

I'm gonna need help on this one. @Forkk?

**Comment by Forkk** [comment]
Disclaimer: I haven't used Bulma before so maybe I am missing some context here.

Neither the `column` class, nor the `pre` tags seem to have anything constraining their width. Setting `max-width` on either, or doing something else to limit their width would fix this.

**Comment by gdude2002** [comment]
This is true, but a simple `max-width` doesn't help b/c you don't know how many columns you might have. On [this page](https://quiltmc.org/staff/outreach/writing/), while I can (for example) set `.column { max-width` to a `vw` value based on breakpoints, this becomes untenable b/c I can't think of a way to match things based on the number of columns -- and even if I could, that'd be an awful lot of work.

There has to be something else here...

**Comment by Forkk** [comment]
Found a much better solution. Just set `min-width: 0` on the `column` elements. Seems to work even with multiple columns.

**Comment by gdude2002** [comment]
Well, I have no idea why the fuck that works, but it does, so, uh, yay?

I added `overflow-x: auto` to `columns` containers as well to address the other overflow issue. Thanks for that!

**Comment by Forkk** [comment]
> Well, I have no idea why the fuck that works, but it does, so, uh, yay?

Apparently flex elements have `min-width` set to `auto` by default (whereas normally it defaults to 0) which causes them to be as wide as their content.

> Thanks for that!

Always happy to help :)
