### ISSUE TITLE
Footer icons not always redirect to the correct page

### ISSUE THREAD

**Issue by mooziii** [QuiltMC/developer-wiki#29]
### Issue description

Some footer icons don't redirect to the correct website.

The Discord icon redirects to the wiki page you're currently on (`href` is set to nothing)
The GitHub icon just redirects to the normal [github.com](https://github.com) page
The Twitch icon just redirects to the normal [twitch.tv](https://twitch.tv) page
The Twitter icon just redirects to the normal [twitter.com](https://twitter.com) page

The other ones are working fine
![image](https://user-images.githubusercontent.com/63669478/180654827-6d003849-b2a2-4f26-b0b6-5d2b9be5bd80.png)
![image](https://user-images.githubusercontent.com/63669478/180654836-e1761820-736c-49dc-8b9a-fe5e45473887.png)
![image](https://user-images.githubusercontent.com/63669478/180654850-60d6daa5-dc75-4365-9406-6916155daecd.png)

**Comment by gdude2002** [comment]
Oh whoops, I forgot to update those when I had to re-import the footer from the old site. I'll fix that.
