### ISSUE TITLE
Items Wiki

### ISSUE THREAD

**Issue by Siuolplex** [QuiltMC/developer-wiki#3]
**What would you like the wiki to cover?**
How to add an Item to the game

**Why should this be added to the wiki?**
Items are very important to the game. A vast majority of content mods add some sort of item.

**Where in the wiki should this go?**
New section: Items

**Comment by mounderfod** [comment]
AFAIK nobody is currently working on this, so I am going to start drafting up some Item documentation :)

**Comment by Mysterious-Dev** [comment]
This issue can be closed with 3bfa8eab813958b273a0a5e9ea657d9b9479520a ?

**Comment by mounderfod** [comment]
> This issue can be closed with [3bfa8ea](https://github.com/QuiltMC/developer-wiki/commit/3bfa8eab813958b273a0a5e9ea657d9b9479520a) ?

Not yet, there is currently only minimal information on Items and I intend to add more

**Comment by olliejohnson** [comment]
Is the Items wiki going to be updated

**Comment by woodiertexas** [comment]
> Is the Items wiki going to be updated
https://modder.wiki.quiltmc.org/items/first-item the new item wiki has been put together as of late.
And there's an "Adding Food" page for those interested: https://modder.wiki.quiltmc.org/items/food
