### ISSUE TITLE
Menus do not work on mobile

### ISSUE THREAD

**Issue by mounderfod** [QuiltMC/developer-wiki#36]
### Operating System

Android

### Web Browser

Firefox

### Issue description

https://user-images.githubusercontent.com/24373708/185189518-294a8e8a-0637-4685-b9af-5a3e63927c9c.mp4

See above.
I haven't tested on other browsers yet but I can do so.

**Comment by Mysterious-Dev** [comment]
This seems to have been fixed.

https://user-images.githubusercontent.com/40738104/189479681-8ee2d29c-5bee-40fa-8a3e-83b2d9fb0175.mp4

**Comment by gdude2002** [comment]
I actually didn't realize there was an issue for this - but yep, I did fix it. Not sure what's up with the link in your viewport, though.
