### ISSUE TITLE
Creating Items

### ISSUE THREAD

**Issue by olliejohnson** [QuiltMC/developer-wiki#47]
### What would you like the wiki to cover?

Add a description on how to add an item to and itemgroup in 1.19.3

### Why should this be added to the wiki?

The Items part of the wiki is very small and the latest version is 1.19.2

### Where in the wiki should this go?

in the Items section

**Comment by AdamGEmerson** [comment]
Hello, 

For 1.19.4 I have found that updating the line:
`Registry.register(Registry.ITEM, new Identifier(mod.metadata().id(), "example_item"), EXAMPLE_ITEM);` 
to use Registries instead:
`Registry.register(Registries.ITEM, new Identifier(mod.metadata().id(), "example_item"), EXAMPLE_ITEM);` 
solves one of the compilation errors.

I have yet to figure out how to add the item group to the `QuiltItemSettings` object though.  It appears the `.group()` method no longer exists for that class.

I'd be happy to update the wiki once I figure this out.

**Comment by AdamGEmerson** [comment]
Items can be added to groups in 1.19.4 as follows:

```java
private static void registerItem() {
    EXAMPLE_ITEM = new Item(new QuiltItemSettings());
    ItemGroupEvents.modifyEntriesEvent(ItemGroups.TOOLS_AND_UTILITIES).register(entries -> {
        entries.addAfter(Items.FLINT, EXAMPLE_ITEM);
    });
}
```

**Comment by woodiertexas** [comment]
There's an items section on the wiki now: https://modder.wiki.quiltmc.org/items/first-item
Tho keep in mind it is still in development. If you want to help out with the wiki, feel free to open a PR.
