### ISSUE TITLE
The  main   branch of  developer-wiki   does not contain the path  wiki/versions/1.19/getting_started/setup/markdown/setup.

### ISSUE THREAD

**Issue by Icequeen3333** [QuiltMC/developer-wiki#49]
### Operating System

Windows

### Web Browser

Chrome

### Issue description

Honestly I could probably do a pull request of this myself, it seems like a simple change, but on both the website and github, when referring to the setup guide, it shows this error message.

`The  main branch of developer-wiki does not contain the path wiki/versions/1.19/getting_started/setup/markdown/setup.`

 I believe because it is trying to find a folder named setup and not setup.md.

**Comment by Icequeen3333** [comment]
Actually, even more interesting, I don't know whether it was intended for you guys to have setup higher up on the tree than migrating from fabric, because on the website they're different than in the code. I won't do the pull request out of clarification. Getting started has nothing in the markdown other than the title, but setup has significantly more, and is above migrating.

**Comment by OroArmor** [comment]
The wiki is in a broken state right now and there will be a rewrite of it to hopefully fix many of the issues (like this one) soon

**Comment by OroArmor** [comment]
Also from a quick look, all that needs to change is adding `.md` at the end of that link

**Comment by Icequeen3333** [comment]
Yep, I forked and did a local change of it, wasn't too big to do, still a clarification issue for me, I'll pull request it.
