### ISSUE TITLE
How to add armor

### ISSUE THREAD

**Issue by Siuolplex** [QuiltMC/developer-wiki#5]
**What would you like the wiki to cover?**
How to add armor items

**Why should this be added to the wiki?**
A lot of first time mods are usually about a new set of armor. Furthermore, the current solution falls short when it comes to attaching new attributes to your armor

**Where in the wiki should this go?**
Section mentioned in #3, Items Section

**Comment by anonymous123-code** [comment]
Im working on this

**Comment by OroArmor** [comment]
Closed with #61
