### ISSUE TITLE
new article: quilt config

### ISSUE THREAD

**Issue by ix0rai** [QuiltMC/developer-wiki#70]
### What would you like the wiki to cover?

quilt config is a fantastic API and needs a comprehensive tutorial!
I'm happy to cover this, since I've now been in the trenches with qconf and understand it very well

### Why should this be added to the wiki?

awesome

### Where in the wiki should this go?

probably a new "quilt tooling" section idk

**Comment by FirstMegaGame4** [comment]
couldn't "quilt loader" be a better section? since qconfig is in it

**Comment by ix0rai** [comment]
that could be a solid idea, we could fill out the section with stuff about using quilt loader APIs

**Comment by OroArmor** [comment]
I do want a more general section for APIs that arent tied to Minecraft. Loader and Config are good examples. Mixin, DFU, and Brigadier are also good libraries to document somewhat separately.

**Comment by FirstMegaGame4** [comment]
With the upcoming inclusion of MixinExtras into the Quilt Loader, a link refering to the MixinExtras' wiki should be good to put in the Mixin Category.
