### ISSUE TITLE
Mention "Quilt Bisect" in a troubleshooting section of the wiki

### ISSUE THREAD

**Issue by woodiertexas** [QuiltMC/developer-wiki#99]
### What would you like the wiki to cover?

Have a mention of https://modrinth.com/mod/quilt-bisect somewhere on a troubleshooting section.

### Why should this be added to the wiki?

To make this tool readily available to help troubleshoot crashes in mod setups.

### Where in the wiki should this go?

A troubleshooting section.

**Comment by ix0rai** [comment]
we have a troubleshooting page on the website (https://quiltmc.org/en/usage/troubleshooting/), that's not a wiki thing
